spring:
   datasource:
      url: jdbc:mysql://127.0.0.1:3306/springjpa-project
      username: root
   driver-class-name: com.mysql.jdbc.Driver
   jpa:
      #show-sql: true
      hibernate:
         ddl-auto: update
   #security:
    #  user:
     #    name: MDF
      #   password: 12345

URLS:
   Authenticated: 
      WithoutRole: /api/student/byEmail,/api/student/update,/api/student/all,/api/student/authorities
      WithBalanceRole: /api/course/**   
   Permitall: /api/student/register